# Generated by Django 5.1.1 on 2024-09-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='country',
            name='flag_png',
        ),
        migrations.RemoveField(
            model_name='country',
            name='flag_svg',
        ),
        migrations.RemoveField(
            model_name='country',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='country',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='country',
            name='official_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='timezone',
        ),
        migrations.AddField(
            model_name='country',
            name='continents',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='flags',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='latlng',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='timezones',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.JSONField(),
        ),
    ]
