# Generated by Django 5.1.1 on 2024-09-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_remove_country_continent_remove_country_flag_png_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='flags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='latlng',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='timezones',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
