# Generated by Django 5.1.1 on 2024-09-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_alter_country_continents_alter_country_flags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='latlng',
        ),
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='official_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='Unnamed Country', max_length=255),
        ),
    ]
