# Generated by Django 5.1.1 on 2024-09-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_remove_country_latlng_country_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continents',
        ),
        migrations.RemoveField(
            model_name='country',
            name='flags',
        ),
        migrations.RemoveField(
            model_name='country',
            name='timezones',
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='flag_png',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='flag_svg',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
