# Generated by Django 5.1.1 on 2024-09-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_remove_country_continents_remove_country_flags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='continent',
            new_name='continents',
        ),
        migrations.RemoveField(
            model_name='country',
            name='timezone',
        ),
        migrations.AddField(
            model_name='country',
            name='timezones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
