# Generated by Django 5.1.1 on 2024-09-14 16:40

import countries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_alter_country_id_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.FloatField(blank=True, null=True, validators=[countries.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(blank=True, null=True, validators=[countries.models.validate_positive]),
        ),
    ]
